import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["./src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron"],
  // xregexp 的发布版依赖 @babel/runtime-corejs3，会打进 core-js 的旧浏览器兼容代码
  //（用 iframe 与 javascript: 地址造对象）。Obsidian 运行环境不需要它，改用其 ES 源码。
  alias: { xregexp: "xregexp/src/index.js" },
  inject: ["./esbuild.injecthelper.mjs"],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  define: {
    global: "window",
    "process.env.NODE_DEBUG": "undefined",
    "process.env.DEBUG": "undefined",
  },
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
